[default]
MONGO_URI = "mongodb://localhost:27017/eve_playground"
S3_BUCKET_NAME = "your-s3-bucket-name"
AWS_ACCESS_KEY_ID = "your-access-key"
AWS_SECRET_ACCESS_KEY = "your-secret-key"
AWS_REGION = "your-region"
LOG_LEVEL = "INFO"

[development]
DEBUG = true

[production]
DEBUG = false
LOG_LEVEL = "WARNING"
